<aside class="col-left sidebar col-sm-3 col-xs-12 col-sm-pull-9 hidden-xs wow bounceInUp animated"> 
        <!-- BEGIN SIDE-NAV-CATEGORY -->
        <div class="side-nav-categories">
          <div class="block-title"> Categories </div>
          <!--block-title--> 
          <!-- BEGIN BOX-CATEGORY -->
          <div class="box-content box-category">
            <ul>
                <?php
                $expandClass = '';
                $display = '';
                foreach ($GLOBALS['category_list']['data'] as $category){    
                    if (!empty($category['category_name'])) {
                        if(!empty($GLOBALS['category_id']) && $GLOBALS['category_id'] == $category['id']) {
                            $expandClass = 'minus';
                            $display = 'block';   
                        }
                    ?>
                        <li> <a class="active" href="<?=$this->basePath()?>/index.php/application/index/product?id=<?=$category['id']?>"><?=$category['category_name'];?></a>
                            <?php
                                if(!empty($category['child'])) {
                            ?>
                                <span class="subDropdown <?=$expandClass?>"></span>
                                <ul class="level0_415" style="display:<?=$display?>">
                                    <?php
                                        foreach($category['child'] as $childcategory){
                                    ?>
                                            <li> <a href="<?=$this->basePath()?>/index.php/application/index/product?id=<?=$childcategory['id']?>"> <?=$childcategory['category_name']?></a> 

                                              <!--level1--> 
                                            </li>                   
                                    <?php
                                        }
                                    ?>
                                </ul> 
                            <?php
                                }
                            ?>
                        </li>
                    <?php
                    }
                    $expandClass = 'plus';
                    $display = "none";
                }
                ?>     
              
            </ul>
          </div>
          <!--box-content box-category--> 
        </div>
        <!--side-nav-categories-->
        
<!--        <div class="custom-slider">
          <div>
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li class="active" data-target="#carousel-example-generic" data-slide-to="0"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
                <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
              </ol>
              <div class="carousel-inner">
                <div class="item active"><img src="images/slide3.jpg" alt="slide3">
                  <div class="carousel-caption">
                    <h3><a title=" Sample Product" href="product-detail.html">50% OFF</a></h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    <a class="link" href="#">Buy Now</a></div>
                </div>
                <div class="item"><img src="images/slide1.jpg" alt="slide1">
                  <div class="carousel-caption">
                    <h3><a title=" Sample Product" href="product-detail.html">Hot collection</a></h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div class="item"><img src="images/slide2.jpg" alt="slide2">
                  <div class="carousel-caption">
                    <h3><a title=" Sample Product" href="product-detail.html">Summer collection</a></h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
              </div>
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"> <span class="sr-only">Previous</span> </a> <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"> <span class="sr-only">Next</span> </a></div>
          </div>
        </div>-->
       
        <div class="block block-list block-cart"   >
          <div class="block-title"> My Cart </div>
          <div class="block-content">
            <div class="summary">
              <p class="amount">There is <a href="#">{{totalItemInCart}} item's</a> in your cart.</p>
              <p class="subtotal"> <span class="label">Cart Subtotal:</span> <span class="price">GHC{{totalPrice}}</span> </p>
            </div>
            <div class="ajax-checkout" ng-if="totalItemInCart">
              <button type="button" title="Checkout" class="button button-checkout" onClick="window.location = '<?=$this->basePath()?>/index.php/application/index/checkout'"> <span>Checkout</span> </button>
            </div>
            <p class="block-subtitle">Recently added item(s)</p>
            <ul id="cart-sidebar" class="mini-products-list">
              <li class="item" ng-repeat="cartItem in cartResponse.data">
                <div class="item-inner"> <a href="#" class="product-image"><img src="{{cartResponse.imageRootPath}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].type}}/{{cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].image_name}}" width="80" alt="product"></a>
                  <div class="product-details">
                      <div class="access"> 
                          <i class="fa fa-plus green-text" ng-click="addToCart(cartItem.merchant_inventry_id, cartItem.item_name, 'add', 1)"></i> 
                          {{cartItem.number_of_item}}
                          <i class="fa fa-minus red-text" ng-click="addToCart(cartItem.merchant_inventry_id, cartItem.item_name, 'delete', 1)"></i>
                      </div>
                    <!--access--> 
                    
                    <strong>{{cartItem.number_of_item}}</strong> x <span class="price">GHC {{cartResponse.productDetails.data[cartItem.merchant_inventry_id].price}}</span>
                    <p class="product-name"><a href="javascript::void(0)">{{cartItem.item_name}}</a></p>
                  </div>
                  <!--product-details-bottoms--> 
                </div>
              </li>
              
            </ul>
          </div>
        </div>
      </aside>