<!DOCTYPE html>
<html lang="en">
<body>
<!-- header -->
<!-- //header -->
<!-- breadcrumbs -->
<div class="container subscribe-right">
  <ol class="breadcrumb breadcrumb1">
    <li><a href="<?=$this->basePath()?>/">Home</a></li>
    <li class="active">About</li>
  </ol>
  <div class="clearfix"> </div>
</div>
<STYLE TYPE="text/css">
	<!--
		@page { margin: 1in }
		.pagehtml P { margin-bottom: 0.08in; direction: ltr; widows: 2; orphans: 2; font-size:13px;color:#000;}
		.pagehtml a:link { color: #689f39; so-language: zxx }
		p.headingpage {
    font-size: 17px;
}
	-->
	</STYLE>
<div class="pagehtml container">
  <p class="headingpage">Online grocery Ghana</p>
  <p>Afro Baskets ltd. is the first comprehensive online grocery store in Ghana. With over 10,000+ products and 700+ brands in our grocery list you will find everything you are looking for. Right from&nbsp;Staples, Beverages, Baby Products and seasonings to packaged bread, bakery and pet food and&nbsp;other&nbsp;<a href="http://www.bigbasket.com/cl/branded-foods/">branded foods online</a>&nbsp;- we have it all. Save time and money, shop at Afrobaskets.com- an all-encompassing online groceries store of Ghana.</p>
  <p class="headingpage">Ghana&rsquo;s Best Online Supermarket</p>
  <p>Shopping with Afrobaskets.com, the best online grocery and Branded food shopping store in Ghana. It is very simple and easy. No more standing in lines, carrying heavy bags and looking for parking! Get started with online grocery shopping at Ghana&rsquo;s favourite online grocery store. Choose from a wide range of options in every groceries list, exclusively handpicked to help you find the best quality available at the lowest prices. Select a time slot for home delivery and your order will be delivered at your doorstep, anywhere in Accra and Tema. In future we are expanding to other cities in Ghana. You can pay by cash, card, Mobile Money. We guarantee on time delivery and the best quality! Happy Shopping!</p>
  <p class="headingpage">Online Grocery Supermarket Ghana</p>
  <p>We, at Afrobaskets.com, are excited about making life simpler and grocery shopping a breeze! Now you can buy&nbsp;<a href="http://www.bigbasket.com/pc/branded-foods/organic-branded-foods/">Breakfast food</a>&nbsp;&amp; grocery online at your leisure and from the comfort of your home - no more standing in the long queues at ration shops, provision stores &amp; supermarkets. Online grocery shopping in Accra and Tema is made easy &amp; simple when you are shopping groceries at Afrobaskets.com.</p>
</div>
</body>
</html>