<!DOCTYPE html>
<html lang="en">
    <body ng-app="app" ng-controller="changepassword">
        <div class="login-page">
            <div class="container"> 
                <h3 class="w3ls-title w3ls-title1 subscribe-right">  Forgot Password</h3> 
                <h4 class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</h4>
                <h4 class="danger" style="color:green" ng-show="successShow">{{successMsg}}</h4>
                <div class="login-body">
                    <form  method="post">
                        <?php
                            if(!empty($this->authkey)){
                                echo'<input type="hidden" class="user" id="auth"  value="'.$this->authkey.'" required="">';
                            }else{
                        ?>
                        <input type="password" class="user" name="password" ng-model="changepasswordData.password" placeholder="Old Password" required="">
                        <?php }?>
                        <input type="password" name="new_password" ng-model="changepasswordData.new_password" class="lock" placeholder="new Password" required="">
                        <input type="password" name="confirm_password" ng-model="changepasswordData.confirm_password" class="lock" placeholder="Confirm Password" required="">
                        <input type="submit" value="Save" ng-click="changepassword(changepasswordData)">
                        
                    </form>
                </div>  
                <h6> Not a Member? <a  href="<?=$this->basePath()?>/index.php/application/index/signup">Sign Up Now »</a> </h6> 
                <div class="login-page-bottom social-icons">
                    <h5>Recover your social account</h5>
                    <ul>
                        <li><a href="#" class="fa fa-facebook icon facebook"> </a></li>
                        <li><a href="#" class="fa fa-twitter icon twitter"> </a></li>
                        <li><a href="#" class="fa fa-google-plus icon googleplus"> </a></li>
                        <li><a href="#" class="fa fa-dribbble icon dribbble"> </a></li>
                        <li><a href="#" class="fa fa-rss icon rss"> </a></li> 
                    </ul> 
                </div>
            </div>
        </div>
        <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
            <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
        </div>
        <!-- //login-page --> 


    </body>
</html>
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() ?>/public/css/style.css">
<script src="<?php echo $this->basePath() . '/public/js/frontend/changepassword.js' ?>">
</script>