
<html lang="en">
    <body ng-app="app" ng-controller="edituser" ng-cloak="true">
        <div class="login-page">
            <div class="container"> 
                <h3 class="w3ls-title w3ls-title1">Edit your account</h3>
                <h4 class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</h4>
                <h4 class="danger" style="color:green" ng-show="successShow">{{successMsg}}</h4> 
                 <div class="clearfix"> </div>
                 <div class="login-body">
                    <form method="post">
                        <input type="text" ng-model="userData.name" class="user" name="name" placeholder="Enter your Name" required="">
                        <input type="text" ng-model="userData.email" class="user" name="email" placeholder="Enter your email" required="">
                        <input type="text" ng-model="userData.mobile_number" maxlength="10" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" class="user" name="mobile" placeholder="Enter your mobile number" required="">
                        <select class="form-control select2 user" style="width: 100%;" ng-model="userData.city_id">
                            <option value=""> Select City</option>
                        <?php
                            foreach ($this->cityList as $key => $value) {
                                echo'<option value="'.$value['id'].'">'.$value['city_name'].'</option>';
                            }
                        ?>
                        </select>
                        
                        <input type="submit" value="Update Profile " ng-click="updateaccount(userData)">
                        
                    </form>
                </div>  
                
            </div>
        </div>
        <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
            <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
        </div>
        <!-- //login-page --> 
    </body>
</html>
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() ?>/public/css/style.css">
<script src="<?php echo $this->basePath() . '/public/js/frontend/edituser.js' ?>">
</script>
<script>
    app.value('userDetails', '<?php echo !empty($this->user_details)?json_encode($this->user_details):'';?>');
</script>