<div class="col-main col-sm-9 col-sm-push-3 product-grid" ng-cloak="true" ng-controller="product">
    <div class="pro-coloumn">
        <article class="col-main">
            <div class="toolbar">
                <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
                    <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?= $this->basePath() ?>/public/images/loading_cart.gif">
                </div>
               
            </div>
            <div class="category-products">
                <ol class="products-list hidden-md hidden-lg" id="products-list">
                    <li class="item first" ng-repeat="product in productDataList track by $index">
                      <div class="product-image"> 
                          <a href="<?=$this->basePath()?>/index.php/application/index/product?id={{product.category_id}}" title="{{product.product_name}}">
                              <img src="{{allProductListResponse.imageRootPath}}/{{allProductListResponse.images[product.category_id][0].type}}/{{allProductListResponse.images[product.category_id][0].image_id}}/{{allProductListResponse.images[product.category_id][0].image_name}}">
                          </a> 
                      </div>
                      <div class="product-shop">
                        <h2 class="product-name">
                            <a href="<?=$this->basePath()?>/index.php/application/index/product?id={{product.category_id}}" title="{{product.product_name}}">{{product.category_name}}</a>
                        </h2>
                           
                        
                      </div>
                    </li>    
                </ol>                
                <ul class="products-grid hidden-xs hidden-sm">
                    <li class="item col-lg-4 col-md-3 col-sm-4 col-xs-6" ng-repeat="product in productDataList track by $index">
                        <div class="item-inner">
                            <div class="item-img">
                                <div class="item-img-info" style="height: 150px;">
                                    <a href="<?=$this->basePath()?>/index.php/application/index/product?id={{product.category_id}}" title="{{product.category_name}}" class="product-image">
                                        <img src="{{allProductListResponse.imageRootPath}}/{{allProductListResponse.images[product.category_id][0].type}}/{{allProductListResponse.images[product.category_id][0].image_id}}/{{allProductListResponse.images[product.category_id][0].image_name}}">
                                    </a>

                                    <div class="item-box-hover">
                                    </div>
                                </div>
                            </div>
                            <div class="item-info">
                                <div class="info-inner">
                                    <div class="item-title">
                                        <a href="<?=$this->basePath()?>/index.php/application/index/product?id={{product.category_id}}" title="{{product.product_name}}">
                                            {{product.category_name}}
                                        </a> 
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                        
                    </li>
                </ul>
            </div>
            <!--div class="pager">                    
                <div class="pages">
                    <label>Page:</label>
                    <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>

                </div>
            </div-->
        </article>
    </div>
    <!--	///*///======    End article  ========= //*/// --> 
</div>
<div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
    <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?= $this->basePath() ?>/public/images/loading_cart.gif">
</div>
<script type="text/javascript" src="<?= $this->basePath() ?>/public/js/frontend/featurecategory.js?v=4"></script>
<script>
    var PAGE_COUNT = 5;
    var PAGING_GAP = 3;    
    app.value('searchBy', <?php echo json_encode($this->searchBy); ?>);
    app.value('page', 'product');
   
</script>
