<div class="right-panel"  ng-cloak="true" ng-controller="product">
    <div class="full-width"> 
        <ol class="breadcrumb breadcrumb1 relative pdp_top-container" >
            <li><a href="#">Home</a></li>
            <li class="active">Hot Deals</li>			
        </ol>

        <div class="clearfix"> </div>
    </div>

    <div class="category-navs">
        <div class="clearfix com-marg"> </div>
        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
    </div>
    <div class="products products--grid">   
        <div ng-show="no_record != ''"> 
            <h4 style="color:red;"> {{no_record}}</h4>
        </div>
        <div class="product_wrapper" ng-repeat="product in productDataList">
            <div class="plp-product">
                <div class="plp-product_offer" ng-if="product.attribute[quantity[product.product_id]].discount_value && product.attribute[quantity[product.product_id]].discount_value!='0'">
                    <span ng-if="product.attribute[quantity[product.product_id]].discount_type!='percent'">GHC </span>{{product.attribute[quantity[product.product_id]].discount_value}}<span ng-if="product.attribute[quantity[product.product_id]].discount_type=='percent'">%</span> OFF</div>
                <div class="plp-product_offer" ng-if="product.discount_value && product.attribute[quantity[product.product_id]].discount_value=='0' && product.discount_value!='0'"><span ng-if="product.discount_type=='flat'">GHC </span>{{product.discount_value}} <span ng-if="product.discount_type=='percent'">%</span> OFF</div>
                <div class="plp-product_offer display--none"></div>
                <div class="plp-product_img ">
                    <img class="img animated fadeIn" src="{{allProductListResponse.imageRootPath}}/{{allProductListResponse.productImageData[product.product_id][0].type}}/{{product.product_id}}/{{allProductListResponse.productImageData[product.product_id][0].image_name}}">
                </div>
                <div class="plp-product_name " title="Economy Dhuli Moong Dal">
                    <div class="LinesEllipsis  plp-product_name--box"><a href="<?=$this->basePath()?>/application/index/productdetails?id={{product.product_id}}-{{quantity[product.product_id]}}">{{product.product_name}}
                        <none ng-if="product.brand_name">({{product.brand_name}})</none>
                        </a><wbr></wbr>
                    </div>
                </div>
                <!--div class="plp-product_quantity" title="1 kg"><span>1 kg</span></div-->
                <div class="plp-product_quantity">                    
                    <select style="border:1px solid #FF3300; border-radius:4px; padding:4px; width:120px;" ng-model="quantity[product.product_id]">
                        <option ng-repeat="attributeDetails in product.attribute track by $index" ng-value="attributeDetails.attribute_id" ng-selected="1">
                            {{setAttribute(attributeDetails, $index)}}
                            {{attributeDetails.quantity}} {{attributeDetails.unit}}
                        </option>
                    </select>  
                </div>                
                <div class="plp-product_price">
                    <div class="plp-product_price--container">
                        <div class="plp-product_price--old display--inline-block@mobile"></div>
                        <div class="plp-product_price--new display--inline-block@mobile">
                            <span ng-if="product.attribute[quantity[product.product_id]].price == product.attribute[quantity[product.product_id]].actual_price">
                                GHC {{product.attribute[quantity[product.product_id]].price}} 
                            </span>
                            <span ng-if="product.attribute[quantity[product.product_id]].price != product.attribute[quantity[product.product_id]].actual_price">
                                <strike>GHC {{product.attribute[quantity[product.product_id]].price}} </strike><br/>
                                GHC {{product.attribute[quantity[product.product_id]].actual_price}}
                            </span>                            
                        </div>
                    </div>
                </div>
                <div class="plp-product_add-to-cart">
                    <div class="add-to-cart">
                        <button class="add-to-cart_dec" data-test-id="minus-button"></button>
                        <button ng-if="!cartResponse.data[product.attribute[quantity[product.product_id]].id].number_of_item" class="add-to-cart_add-btn display--inline-block" data-test-id="add-button" ng-click="addToCart(product.attribute[quantity[product.product_id]].id, product.product_name, 'add', 1)">Add To Cart</button>
                        <span ng-if="cartResponse.data[product.attribute[quantity[product.product_id]].id].number_of_item">
                        <i class="fa fa-plus green-text" ng-click="addToCart(product.attribute[quantity[product.product_id]].id, product.product_name, 'add', 1)"></i> 
                        <b>&nbsp;{{cartResponse.data[product.attribute[quantity[product.product_id]].id].number_of_item}}&nbsp;</b>
                        <i class="fa fa-minus red-text" ng-click="addToCart(product.attribute[quantity[product.product_id]].id, product.product_name, 'delete', 1)"></i>                       
                        </span>
                        <button class="add-to-cart_inc" data-test-id="plus-button"></button>
                    </div>
                    
                </div>
            </div>
        </div>               
    </div>     
        <div class="row">
            <div class="col-sm-4">
                <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Total {{numberOfRecord}} entries</div>
            </div>
            <div class="col-sm-8" ng-show="numberOfRecord>10">
                <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                    <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                </div>
            </div>
        </div>	
</div>
</div>
</div>
<div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
    <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
</div>	
<script src="<?php echo $this->basePath() . '/public/js/frontend/product.js' ?>">
</script>
<script>
    var PAGE_COUNT = 5;
    var PAGING_GAP = 3;    
    app.value('searchBy', <?php echo json_encode($this->searchBy); ?>);
    app.value('page', 'hotdeals');
</script>