  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
     <div class="page-title">
     <h2>Login or Create an Account</h2>
  </div>
        </div>
        <!--col-xs-12-->
      </div>
      <!--row-->
    </div>
    <!--container-->
  </div>
<div class="main-container col1-layout wow bounceInUp animated animated" style="visibility: visible;" ng-controller="login">     

    <div class="main">                     
        <div class="account-login container">
            <!--page-title-->

            <form action="" method="post" id="login-form">
                <input name="form_key" type="hidden" value="EPYwQxF6xoWcjLUr">
                <fieldset class="col2-set">
                    <div class="col-1 new-users"> 
                        <strong>New Customers</strong>    
                        <div class="content">

                            <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
                            <div class="buttons-set">
                                <button type="button" title="Create an Account" class="button create-account"><a href="<?=$this->basePath()?>/index.php/application/index/signup"><span>Create an Account</span></a></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 registered-users">
                        <strong>Registered Customers</strong>             
                        <div class="content">

                            <p>If you have an account with us, please log in.</p>
                            <ul class="form-list">
                                <li>
                                    <label for="email">Email Address<em class="required">*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="email" ng-model="loginData.email" value="" id="email" class="input-text required-entry validate-email" title="Email Address">
                                    </div>
                                </li>
                                <li>
                                    <label for="pass">Password<em class="required">*</em></label>
                                    <div class="input-box">
                                        <input type="password"  name="password" ng-model="loginData.password" class="input-text required-entry validate-password" id="pass" title="Password">
                                    </div>
                                </li>
                            </ul>
                            <div class="remember-me-popup">
                                <div class="remember-me-popup-head" style="display:none">
                                    <h3 id="text2">What's this?</h3>
                                    <a href="#" class="remember-me-popup-close" onClick="showDiv()" title="Close">Close</a>
                                </div>
                                <div class="remember-me-popup-body" style="display:none">
                                    <p id="text1">Checking "Remember Me" will let you access your shopping cart on this computer when you are logged out</p>
                                    <div class="remember-me-popup-close-button a-right">
                                        <a href="#" class="remember-me-popup-close button" title="Close" onClick="
                                                showDiv()"><span>Close</span></a>
                                    </div>
                                </div>
                            </div>

                            <p class="required">* Required Fields</p>



                            <div class="buttons-set">

                                <button class="button login" title="Login" name="send" id="send2" ng-click="login(loginData)"><span>Login</span></button>
                                

                                <a href="<?=$this->basePath()?>/index.php/application/index/forgetpassword" class="forgot-word">Forgot Your Password?</a>
                            </div> <!--buttons-set-->
                        </div> <!--content-->                               
                    </div> <!--col-2 registered-users-->
                </fieldset> <!--col2-set-->
            </form>

        </div> <!--account-login-->

    </div><!--main-container-->

</div> 




<div class="our-features-box wow bounceInUp animated animated">
    <div class="container">
        <ul>
            <li>
                <div class="feature-box free-shipping">
                    <div class="icon-truck"></div>
                    <div class="content">FREE SHIPPING on order over $99</div>
                </div>
            </li>
            <li>
                <div class="feature-box need-help">
                    <div class="icon-support"></div>
                    <div class="content">Need Help +1 800 123 1234</div>
                </div>
            </li>
            <li>
                <div class="feature-box money-back">
                    <div class="icon-money"></div>
                    <div class="content">Money Back Guarantee</div>
                </div>
            </li>
            <li class="last">
                <div class="feature-box return-policy">
                    <div class="icon-return"></div>
                    <div class="content">30 days return Service</div>
                </div>
            </li>
        </ul>
    </div>
</div>
<script src="<?php echo $this->basePath() . '/public/js/frontend/login.js?v=0.01' ?>">
</script>