		<div ng-controller="login">
        <div class="login-page">
            <div class="container"> 
                <h3 class="w3ls-title w3ls-title1 subscribe-right">  Login to your account</h3> 
                <h4 class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</h4>
                <h4 class="danger" style="color:green" ng-show="successShow">{{successMsg}}</h4>
                <div class="login-body">
                    <form  method="post"><br/>
                    <a href="<?=$this->googleLink?>"><img src="<?=$this->basePath()?>/public/images/google-g-icon-12.jpg" height="25"/><b>&nbsp;GOOGLE</b></a>&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="<?=$this->fbLoginUrl?>"><img src="<?=$this->basePath()?>/public/images/fb.png" height="30"/><b>&nbsp;FACEBOOK</b></a>
            	<br/><br/>
            	OR<br/><br/>
                        <input type="text" class="user" name="email" ng-model="loginData.email" placeholder="Enter your email" required="">
                        <input type="password" name="password" ng-model="loginData.password" class="lock" placeholder="Password" required="">
                        <input type="submit" value="Login" ng-click="login(loginData)">
                        
                        <div class="forgot-grid">
                            <!--<label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Remember me</label>-->
                            <div class="forgot">
                                <a href="<?=$this->basePath()?>/index.php/application/index/forgetpassword">Forgot Password?</a>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </form>
                </div>  
                <h6> Not a Member? <a  href="<?=$this->basePath()?>/index.php/application/index/signup">Sign Up Now »</a> </h6> 
                
            </div>
        </div>
        <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
            <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
        </div>
    </div>
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() ?>/public/css/style.css">
<script src="<?php echo $this->basePath() . '/public/js/frontend/login.js?v=0.01' ?>">
</script>
