<div class="right-panel"  ng-cloak="true" ng-controller="merchant">
    <div class="full-width"> 
        <ol class="breadcrumb breadcrumb1 relative pdp_top-container" >
            <li><a href="#">Home</a></li>
            <li class="active"><?= $this->categoryName ?></li>	
            <div class="pull-right">
                <div class="plp-sort-dd">                  
                    <label class="dropdown_title-label" for="dd-title-label">Sort by</label>
                    <select>
                        <option>Relevance</option>
                        <option>Low to High</option>
                        <option>High to Low</option>
                        <option>Name (A To Z)</option>
                    </select>
                </div>
            </div>		
        </ol>

        <div class="clearfix"> </div>
    </div>

    <div class="category-navs">
        <div class="clearfix com-marg"> </div>
        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
    </div>
    <div class="products products--grid">   
        <div ng-show="no_record != ''"> 
            <h4 style="color:red;"> {{no_record}}</h4>
        </div>
        <div class="product_wrapper" ng-repeat="data in merchantDataList">

            <div class="plp-product">
                <div class="plp-product_img ">
                    <img class="img animated fadeIn" src="<?php echo $this->basePath() ?>/public/images/newimg/noimagemerchant.jpeg">
                </div>
                <div class="plp-product_name " title="{{data.first_name}}">
                    <div class="LinesEllipsis  plp-product_name--box"><a href="<?= $this->basePath() ?>/index.php/application/index/product?merchant={{data.user_id}}">{{data.first_name}}</a><wbr></wbr>
                    </div>
                </div>
                
                <div class="plp-product_add-to-cart">
                    <div class="add-to-cart">
                        <a href="<?= $this->basePath() ?>/index.php/application/index/product?merchant={{data.user_id}}">
                            <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Shop Now</button>
                        </a>

                    </div>
                </div>
            </div>
        </div>               
    </div> 
    <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
        <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?= $this->basePath() ?>/public/images/loading_cart.gif">
    </div>    
    <div class="row">
        <div class="col-sm-4">
            <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Total {{numberOfRecord}} entries</div>
        </div>
        <div class="col-sm-8" ng-show="numberOfRecord > 10">
            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
            </div>
        </div>
    </div>
    <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
        <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?= $this->basePath() ?>/public/images/loading_cart.gif">
    </div>	
</div>
</div>
</div>   
<script src="<?php echo $this->basePath() . '/public/js/frontend/merchant.js' ?>">
</script>
<script>
    var PAGE_COUNT = 5;
    var PAGING_GAP = 3;
</script>