  <div class="main-container col1-layout wow bounceInUp animated" ng-controller="productdetails">
    <div class="main">
      <div class="col-main">
        <!-- Endif Next Previous Product -->
        <div class="product-view wow bounceInUp animated" itemscope="" itemtype="http://schema.org/Product" itemid="#product_base">
          <div id="messages_product_view"></div>
          <!--product-next-prev-->
          <div class="product-essential container">
            <div class="row">
              <div class="product-next-prev"> <a class="product-next" title="Next" href="#"><span></span></a> <a class="product-prev" title="Previous" href="#"><span></span></a> </div>
              <form action="" method="post" id="product_addtocart_form">
                <!--End For version 1, 2, 6 -->
                <!-- For version 3 -->
                <div class="product-img-box col-sm-6 col-xs-12">
                  <div class="new-label new-top-left"> New </div>
                  <div class="product-image">
                    <div class="large-image"> <a href="<?=$this->productImage?>" class="cloud-zoom" id="zoom1" rel="useWrapper: false, adjustY:0, adjustX:20"> <img src="<?=$this->productImage?>"> </a> </div>
                    <div class="flexslider flexslider-thumb">
                      <ul class="previews-list slides">
                        <?php
                            foreach($this->productImageList as $image){
                        ?>
                        <li><a href="<?php echo $this->imageRootPath."/".$image['type']."/".$image['image_id']."/".$image['image_name']?>" class='cloud-zoom-gallery' rel="useZoom: 'zoom1', smallImage: '<?php echo $this->imageRootPath."/".$image['type']."/".$image['image_id']."/".$image['image_name']?>' "><img src="<?php echo $this->imageRootPath."/".$image['type']."/".$image['image_id']."/".$image['image_name']?>" alt = "Thumbnail 1"/></a></li>                    
                        <?php
                            }
                        ?>
                      </ul>
                    </div>
                  </div>
                  <!-- end: more-images -->
                </div>
                <!--End For version 1,2,6-->
                <!-- For version 3 -->
                <div class="product-shop col-sm-6 col-xs-12">
                
                  <div class="product-name">
                    <h1 itemprop="name"><?= !empty($this->productDetails['product_name'])?$this->productDetails['product_name']:''?></h1>
                  </div>
                  <!--product-name-->
                  
                <?php 
                    if(!empty($this->productDetails['attribute'])){
//                                        foreach ($this->productDetails['attribute'][$this->selectedAttr] as $key => $value) {
                            $price = $this->productDetails['attribute'][$this->selectedAttr]['price'];
                            $actualPrice = $this->productDetails['attribute'][$this->selectedAttr]['actual_price'];
                            $id = $this->productDetails['attribute'][$this->selectedAttr]['id'];
//                                        }
                    }
                ?>                  
                  <div class="price-block">
                    <div class="price-box"> <span class="regular-price" id="product-price-123"> <span class="price">GHC<?= $actualPrice?></span> </span> </div>
                    <p class="availability in-stock">
                      <link itemprop="availability" href="http://schema.org/InStock">
                      <span>In stock</span></p>
                  </div>
                  <!--price-block-->
                  <div class="short-description">
                    <p><?= !empty($this->productDetails['product_desc'])?"<h2>Quick Overview</h2>".$this->productDetails['product_desc']:''?></p>
                  </div>
                  <div class="add-to-box">
                    <div class="add-to-cart" >
                      <div class="pull-left">
                        <div class="custom pull-left">
                            <form >
                                <input type="hidden" name="number_of_item" value="1" />
                                <input type="hidden" name="action" value="add" /> 
                                <input type="hidden" name="item_name" value="<?=$this->productDetails['product_name']?>" /> 
                                <input type="hidden" name="merchant_inventry_id" value="<?=$id?>" /> 
                                <input type="hidden" name="gotoproductpage" value="<?=$this->productDetails['category_id']?>" />                                 
<!--                                <button onClick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;" class="increase items-count" type="button"  ng-click="addtocart('<?=$this->productDetails['product_id']?>','<?=$this->productDetails['product_name']?>','<?=$id?>')" ><i class="icon-plus">&nbsp;</i></button>
                                <input type="text" name="qty" id="qty" maxlength="12" value="1" title="Quantity:" class="input-text qty">
                                <button onClick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 0 ) result.value--;return false;" class="reduced items-count" type="button"><i class="icon-minus">&nbsp;</i></button>-->
                            </form>                            
                        </div>
                        <!--custom pull-left-->
                      </div>
                        {{product}}
                        <button class="button btn-cart" type="button" ng-if="!cartResponse.data['<?=$id?>'].number_of_item" ng-click="addToCart('<?=$id?>','<?=$this->productDetails['product_name']?>','add', 1)" title="Add to Cart" class="button btn-cart"><span><i class="icon-basket"></i>Add to Cart</span></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="tel:+233553354848" style="margin-top:5px;display:block;font-size:20px;" class="hidden-lg hidden-md">&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-phone" aria-hidden="true"></i></a>
                        <span ng-if="cartResponse.data['<?=$id?>'].number_of_item">
                            <i class="fa fa-plus green-text" ng-click="addToCart('<?=$id?>', '<?=$this->productDetails['product_name']?>', 'add', 1)"></i> 
                            <b>&nbsp;{{cartResponse.data['<?=$id?>'].number_of_item}}&nbsp;</b>
                            <i class="fa fa-minus red-text" ng-click="addToCart('<?=$id?>', '<?=$this->productDetails['product_name']?>', 'delete', 1)"></i>                       
                        </span>
                        <!--pull-left-->  
                      
                    </div>
                    <!--add-to-cart-->
                    
                    
                  </div>
                  <!--add-to-box-->
                  <!-- thm-mart Social Share-->
                  <!--div class="social">
                    <ul class="link">
                      <li class="fb"> <a href="http://www.facebook.com/" rel="nofollow" target="_blank" style="text-decoration:none;"> </a> </li>
                      <li class="linkedin"> <a href="http://www.linkedin.com/" rel="nofollow" target="_blank" style="text-decoration:none;"> </a> </li>
                      <li class="tw"> <a href="http://twitter.com/" rel="nofollow" target="_blank" style="text-decoration:none;"> </a> </li>
                      <li class="pintrest"> <a href="http://pinterest.com/" rel="nofollow" target="_blank" style="text-decoration:none;"> </a> </li>
                      <li class="googleplus"> <a href="https://plus.google.com/" rel="nofollow" target="_blank" style="text-decoration:none;"> </a> </li>
                    </ul>
                  </div-->
                  <!-- thm-mart Social Share Close-->
                </div>
                <!--product-shop-->
                <!--Detail page static block for version 3-->
              </form>
            </div>
          </div>
          <!--product-essential-->
          <div class="product-collateral container">
            <ul id="product-detail-tab" class="nav nav-tabs product-tabs">
              <li class="active"> <a href="#product_tabs_description" data-toggle="tab"> Product Description </a> </li>
              <?php if(!empty($this->productDetails['custom_info'])){              ?>
              <li> <a href="#product_tabs_custom" data-toggle="tab">Additional Info</a> </li>              
             <?php } ?>
            </ul>
            <div id="productTabContent" class="tab-content">
              <div class="tab-pane fade in active" id="product_tabs_description">
                <div class="std">
                  <p><?= !empty($this->productDetails['product_desc']) ? $this->productDetails['product_desc'] : '' ?></p>                                    
                  <?php
                  if (!empty($this->productDetails['bullet_desc'])) {
                      echo "<ul style='margin-left:15px;'>";
                      foreach ($this->productDetails['bullet_desc'] as $bullets) {
                          echo "<li> $bullets</li>";
                      }
                      echo "</ul>";
                  }
                  ?>                  
                </div>
              </div>           

              <div class="tab-pane fade" id="product_tabs_custom">
                <div class="product-tabs-content-inner clearfix">
                    <p>
                        <?php
                        if(!empty($this->productDetails['custom_info'])){
                            foreach ($this->productDetails['custom_info'] as $key => $value) {
                                echo $key .' : ' .$value.'<br>';
                            }
                        }
                        ?>                        
                    </p>                 
                </div>
              </div>
            </div>
          </div>
     
      
          <!--product-collateral-->
         
          <!-- end related product -->
        </div>
        <!--box-additional-->
        <!--product-view-->
      </div>
    </div>
    <!--col-main-->
  </div>
<link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/flexslider.css" media="all">

  <!--main-container-->
  <script type="text/javascript" src="<?=$this->basePath()?>/public/js/jquery.flexslider.js"></script>
  <script type="text/javascript" src="<?=$this->basePath()?>/public/js/cloud-zoom.js"></script>
  
    <script src="<?php echo $this->basePath() . '/public/js/frontend/productdetails.js' ?>">
</script>
