  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
     <div class="page-title">
     <h2>Login or Create an Account</h2>
  </div>
        </div>
        <!--col-xs-12-->
      </div>
      <!--row-->
    </div>
    <!--container-->
  </div>
<div class="main-container col1-layout wow bounceInUp animated animated" style="visibility: visible;" ng-controller="login">     

    <div class="main">                     
        <div class="account-login container">
            <!--page-title-->

            <form action="" method="post" id="login-form">
                <input name="form_key" type="hidden" value="EPYwQxF6xoWcjLUr">
                <fieldset class="col2-set">
                    <div class="col-1 new-users"> 
                        <strong>Registered Customers</strong>    
                        <div class="content">

                            <p>By Login with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
                            <div class="buttons-set">
                                <button type="button" title="Login" class="button create-account"><a href="<?=$this->basePath()?>/index.php/application/index/login"><span>Login</span></a></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 registered-users">
                        <strong>New Customers</strong>             
                        <div class="content">

                            <p>If you have not an account with us, please Register.</p>
                            <ul class="form-list">
                                <li>
                                    <label for="name">Enter your Name<em class="required">*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="name" ng-model="signupData.name" value="" id="name" class="input-text required-entry validate-name" title="">
                                    </div>
                                </li>
                                <li>
                                    <label for="email">Email Address<em class="required">*</em></label>
                                    <div class="input-box">
                                        <input type="text" name="email" ng-model="signupData.email" value="" id="email" class="input-text required-entry validate-email" title="Email Address">
                                    </div>
                                </li>
                                <li>
                                    <label for="email">Enter your mobile number<em class="required">*</em></label>
                                    <div class="input-box">
                                        <input type="text" ng-model="signupData.phonecode" class=" input-text required-entry validate-number" name="phonecode_de" style="width: 20%;float: left;border-right: none;" placeholder="+233" ng-readonly="true">
                                        <input type="text" name="number" ng-model="signupData.mobile_number" maxlength="10" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" value="" id="email" class="input-text required-entry validate-number" title="Email Address">
                                    </div>
                                </li>
                                 <li>
                                    <label for="email">Select City<em class="required">*</em></label>
                                    <div class="input-box">
                                       <select class="form-control select2 user" style="width: 100%;" ng-model="signupData.city_id">
                                            <option value=""> Select City</option>
                                        <?php
                                            foreach ($this->cityList as $key => $value) {
                                                echo'<option value="'.$value['id'].'">'.$value['city_name'].'</option>';
                                            }
                                        ?>
                                         </select>
                                    </div>
                                </li>
                                
                                <li>
                                    <label for="pass">Password<em class="required">*</em></label>
                                    <div class="input-box">
                                        <input type="password"  name="password" ng-model="signupData.password" class="input-text required-entry validate-password" id="pass" title="Password">
                                    </div>
                                </li>
                            </ul>
                            

                            <p class="required">* Required Fields</p>



                            <div class="buttons-set">

                                <button class="button login" title="Login" name="send" id="send2" ng-click="createaccount(signupData)"><span>Regiter</span></button>
                                

                                
                            </div> <!--buttons-set-->
                        </div> <!--content-->                               
                    </div> <!--col-2 registered-users-->
                </fieldset> <!--col2-set-->
            </form>

        </div> <!--account-login-->

    </div><!--main-container-->

</div> 




<div class="our-features-box wow bounceInUp animated animated">
    <div class="container">
        <ul>
            <li>
                <div class="feature-box free-shipping">
                    <div class="icon-truck"></div>
                    <div class="content">FREE SHIPPING on order over $99</div>
                </div>
            </li>
            <li>
                <div class="feature-box need-help">
                    <div class="icon-support"></div>
                    <div class="content">Need Help +1 800 123 1234</div>
                </div>
            </li>
            <li>
                <div class="feature-box money-back">
                    <div class="icon-money"></div>
                    <div class="content">Money Back Guarantee</div>
                </div>
            </li>
            <li class="last">
                <div class="feature-box return-policy">
                    <div class="icon-return"></div>
                    <div class="content">30 days return Service</div>
                </div>
            </li>
        </ul>
    </div>
</div>
<script src="<?php echo $this->basePath() . '/public/js/frontend/login.js?v=0.01' ?>">
</script>