<!DOCTYPE html>
<html lang="en">
<body>
<!-- header -->
<!-- //header -->
<!-- breadcrumbs -->
<div class="container subscribe-right">
  <ol class="breadcrumb breadcrumb1">
    <li><a href="<?=$this->basePath()?>/">Home</a></li>
    <li class="active">Terms and Conditions</li>
  </ol>
  <div class="clearfix"> </div>
</div>
<STYLE TYPE="text/css">
	<!--
		@page { margin: 1in }
		.pagehtml P { margin-bottom: 0.08in; direction: ltr; widows: 2; orphans: 2; font-size:13px;color:#000;}
		.pagehtml a:link { color: #689f39; so-language: zxx }
		p.headingpage {
    font-size: 17px;
}
	-->
	</STYLE>
<div class="pagehtml container">
  <p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">INTRODUCTION</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
normal"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN"><br>
<span style="background:white">Welcome to afrobaskets.com website (the
"Site"). These terms and conditions ("Terms and
Conditions") apply to the Site, and all of its divisions, subsidiaries,
and affiliate operated Internet sites which reference these Terms and
Conditions.</span><br>
<br>
<span style="background:white">By accessing the Site, you confirm your
understanding of the Terms and Conditions. If you do not agree to these Terms
and Conditions of use, you shall not use this website. The Site reserves the
right, to change, modify, add, or remove portions of these Terms and Conditions
of use at any time. Changes will be effective when posted on the Site with no
other notice provided. Please check these Terms and Conditions of use regularly
for updates. Your continued use of the Site following the posting of changes to
these Terms and Conditions of use constitutes your acceptance of those changes.</span><br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">USE OF THE SITE</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">You are either at least 18 years of age or are accessing the Site under
the supervision of a parent or legal guardian.We grant you a non-transferable
and revocable license to use the Site, under the Terms and Conditions
described, for the purpose of shopping for personal items sold on the Site.
Commercial use or use on behalf of any third party is prohibited, except as
explicitly permitted by us in advance. Any breach of these Terms and Conditions
shall result in the immediate revocation of the license granted in this
paragraph without notice to you.<br>
<br>
Content provided on this site is solely for informational purposes. Product
representations expressed on this Site are those of the vendor and are not made
by us. Submissions or opinions expressed on this Site are those of the
individual posting such content and may not reflect our opinions.<br>
<br>
Certain services and related features that may be made available on the Site
may require registration or subscription. Should you choose to register or
subscribe for any such services or related features, you agree to provide
accurate and current information about yourself, and to promptly update such
information if there are any changes. Every user of the Site is solely
responsible for keeping passwords and other account identifiers safe and
secure. The account owner is entirely responsible for all activities that occur
under such password or account. Furthermore, you must notify us of any
unauthorized use of your password or account. The Site shall not be responsible
or liable, directly or indirectly, in any way for any loss or damage of any
kind incurred as a result of, or in connection with, your failure to comply
with this section.<br>
<br>
During the registration process you agree to receive promotional emails from
the Site. You can subsequently opt out of receiving such promotional e-mails by
clicking on the link at the bottom of any promotional email.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">USER SUBMISSIONS</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">Anything that you submit to the Site and/or provide to us, including but
not limited to, questions, reviews, comments, and suggestions (collectively,
"Submissions") will become our sole and exclusive property and shall
not be returned to you. In addition to the rights applicable to any Submission,
when you post comments or reviews to the Site, you also grant us the right to
use the name that you submit, in connection with such review, comment, or other
content. You shall not use a false e-mail address, pretend to be someone other
than yourself or otherwise mislead us or third parties as to the origin of any
Submissions. We may, but shall not be obligated to, remove or edit any
Submissions.<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">ORDER ACCEPTANCE
AND PRICING</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:
&quot;Arial&quot;,sans-serif;mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;
mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">Please note that there are cases when an order cannot be processed for
various reasons. The Site reserves the right to refuse or cancel any order for
any reason at any given time. You may be asked to provide additional
verifications or information, including but not limited to phone number and
address, before we accept the order.<br>
<br>
In order to avoid any fraud with credit or debit cards, we reserve the right to
obtain validation of your payment details before providing you with the product
and to verify the personal information you shared with us. This verification
can take the shape of an identity, place of residence or banking information
check. The absence of an answer following such a demand will automatically
cause the cancellation of the order within 2 days.We reserve the right to
proceed to direct cancellation of an order for which we suspect a risk of
fraudulent use of credit or debit card.<br>
<br>
We are determined to provide the most accurate pricing information on the Site
to our users; however, errors may still occur, such as cases when the price of
an item is not displayed correctly on the website. As such, we reserve the
right to refuse or cancel any order. In the event that an item is mispriced, we
may, at our own discretion, either contact you for instructions or cancel your
order and notify you of such cancellation. We shall have the right to refuse or
cancel any such orders whether or not the order has been confirmed and your
credit card charged.<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">TRADEMARKS AND
COPYRIGHTS</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">All intellectual property rights, whether registered or unregistered, in
the Site, information content on the Site and all the website design,
including, but not limited to text, graphics, software, photos, video, music,
sound, and their selection and arrangement, and all software compilations,
underlying source code and software shall remain our property. The entire
contents of the Site also are protected by copyright as a collective work under
Ghanaian copyright laws and international conventions. All rights are reserved.<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">ARBITRATIONS</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">Any disputes, controversies, or differences arising out of the
implementation, interpretation, performance of these Terms and Conditions,
shall be finally settled through arbitration by a single arbitrator to be
appointed in accordance with the rules of Chartered Institute of Arbitrators.
The arbitrator shall be a person who is legally trained and who has experience
in the information technology field and is independent of either party. The
venue of the arbitration shall be Nairobi. The language used in the arbitration
proceedings shall be English. The award of the arbitrator shall be final and
binding and may be entered in any court of competent jurisdiction and enforced
in accordance with the Arbitration Act 1995 Chapter No. 4. Notwithstanding the
foregoing, the Site reserves the right to pursue the protection of intellectual
property rights and confidential information through injunctive or other
equitable relief through competent courts.</span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">APPLICABLE LAW AND
JURISDICTION</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:
&quot;Arial&quot;,sans-serif;mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;
mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">These Terms and Conditions shall be interpreted and governed by the laws
in force in Ghana. Each party hereby agrees to submit to the jurisdiction of
the Ghanaians courts and to waive any objections based upon venue. <br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">TERMINATION</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">In addition to any other legal or equitable remedies, we may, without
prior notice to you, immediately terminate the Terms and Conditions or revoke
any or all of your rights granted under the Terms and Conditions. Upon any
termination of this Agreement, you shall immediately cease all access to and
use of the Site and we shall, in addition to any other legal or equitable
remedies, immediately revoke all password(s) and account identification issued
to you and deny your access to and use of this Site in whole or in part. Any
termination of this agreement shall not affect the respective rights and
obligations (including without limitation, payment obligations) of the parties
arising before the date of termination. You furthermore agree that the Site
shall not be liable to you or to any other person as a result of any such
suspension or termination. If you are dissatisfied with the Site or with any
terms, conditions, rules, policies, guidelines, or practices of Jade E Services
in operating the Site, your sole and exclusive remedy is to discontinue using
the Site.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-IN"><o:p>&nbsp;</o:p></span></p></div>
</body>
</html>