    <div ng-controller="login">
        <div class="login-page">
            <div class="container"> 
                <h3 class="w3ls-title w3ls-title1 subscribe-right">  Verify to your Otp</h3> 
                <h4 class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</h4>
                <h4 class="danger" style="color:green" ng-show="successShow">{{successMsg}}</h4>
                <div class="login-body">
                    <form  method="post">
                        <input type="text" class="user" name="otp" ng-model="loginData.otp" placeholder="Enter your otp" required="">
                        
                        <input type="submit" value="Login" ng-click="otp(loginData)">
                        <div class="forgot-grid">
                            <!--<label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Remember me</label>-->
                            
                            <div class="clearfix"> </div>
                        </div>
                    </form>
                </div>  
            </div>
        </div>
        <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
            <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
        </div>
    </div>
<script src="<?php echo $this->basePath() . '/public/js/frontend/login.js' ?>">
</script>
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() ?>/public/css/style.css">